[package]
name = "RFemurServer"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
rand = "0.9.0"
random-string = "1.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
